name: replacer
description: 'A new Flutter project.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_riverpod:
    flutter_hooks:
    hooks_riverpod:
    riverpod_annotation:
    go_router:
    freezed_annotation:
    json_annotation:
    shared_preferences:
    sqflite:
    cupertino_icons: ^1.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    freezed:
    build_runner:
    riverpod_generator:
    json_serializable:
    flutter_lints: ^2.0.0

flutter:
    fonts:
        - family: InterTight
          fonts:
              - asset: assets/fonts/Inter_Tight/static/InterTight-Black.ttf
                weight: 900
              - asset: assets/fonts/Inter_Tight/static/InterTight-Bold.ttf
                weight: 700
              - asset: assets/fonts/Inter_Tight/static/InterTight-Medium.ttf
                weight: 500
              - asset: assets/fonts/Inter_Tight/static/InterTight-Regular.ttf
                weight: 400
    uses-material-design: true

    assets:
        - assets/images/
